name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this application repo
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Build
        shell: bash
        run:  npm run build
      - name: Deploy app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: dist/*
          target: ${{ secrets.TARGET }}
          rm: true
      - name: Move files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script:  cd ${{ secrets.TARGET }} && mv dist/* ./ && rm -rf dist